Repository mm-easy/mm-easy, pull requests merged in 2024-04, with the labels that each got.

#12 [feat] PageUp 버튼 컴포넌트 추가
  src/components/common/PageUpBtn.tsx
  src/components/quiz-form/QuizForm.tsx
  src/types/quizzes.ts
  src/utils/supabase/middleware.ts
Labels: 개발

#14 [feat] utils\supabase\create-client 파일 추가 및 브랜치 세팅
  package.json
  src/app/(community)/community-detail/page.tsx
  src/app/(community)/community-list/page.tsx
  src/app/(community)/community-post/page.tsx
  src/app/community/page.tsx
  src/components/community/community-comment/CommentForm.tsx
  src/components/community/community-form/CommunityForm.tsx
  src/components/community/community-form/PostForm.tsx
  src/components/community/like/Like.tsx
  src/utils/supabase/client.ts
  src/utils/supabase/create-client.ts
  src/utils/supabase/server.ts
  yarn.lock
Labels: 개발, 문서

#17 [feat] 로그인,회원가입 폼, 회원가입 기능구현
  src/app/(non-auth)/login/page.tsx
  src/app/(non-auth)/signup/page.tsx
  src/app/layout.tsx
  src/hooks/useAuth.ts
Labels: 개발, 수정

#19 [feat] QuizForm 에서 가져온 questions useState로 QuestionForm 구성
  src/components/quiz-form/QuestionForm.tsx
  src/components/quiz-form/QuizForm.tsx
  src/types/quizzes.ts
Labels: 개발

#21 [feat] 회원가입시 profiles 에 정보 추가, 로그인 기능 구현
  src/app/(non-auth)/login/page.tsx
  src/app/(non-auth)/signup/page.tsx
  src/components/layout/Header.tsx
  src/hooks/useAuth.ts
  src/types/users.ts
Labels: 개발, 수정, 버그

#23 [feat] supabase posts 데이터 불러오기
  package.json
  src/api/posts.ts
  src/app/(community)/(components)/CommentForm.tsx
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/(community)/(components)/Like.tsx
  src/app/(community)/(components)/PostForm.tsx
  src/app/(community)/community-list/page.tsx
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/(quiz)/quiz-form/page.tsx
  src/components/community/community-form/CommunityForm.tsx
  src/types/posts.ts
  yarn.lock
Labels: 개발, 수정, 세팅

#25 [feat ,design] 구글 로그인 구현, 로그인 페이지 디자인 수정
  src/app/(community)/community-list/page.tsx
  src/app/(non-auth)/login/page.tsx
  src/hooks/useAuth.ts
Labels: 개발, 수정

#28 [feat] question 타이틀, 주관식 정답 입력하면 setState 되도록 & 라디오 오류 수정
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
Labels: 수정

#29 [feat] quiz-form 페이지에서 '등록하기' 버튼 클릭 시 처리
  src/api/quizzes.ts
  src/app/(quiz)/(components)/Header.tsx
  src/app/(quiz)/(components)/PlusQuestionBtn.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/(quiz)/quiz-form/page.tsx
  src/components/common/BlueInput.tsx
  src/components/common/PageUpBtn.tsx
  src/types/quizzes.ts
  src/utils/generateFileName.ts
Labels: 개발, 수정

#31 [feat] 선택지 입력값 quiz 의 useState 에 반영되게
  next.config.mjs
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
Labels: 개발, 수정, 세팅

#32 [style] Header & Footer 임시 스타일링
  src/api/quizzes.ts
  src/app/(quiz)/(components)/QuizForm.tsx
  src/components/common/BlueInput.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
Labels: 개발, 수정

#33 [feat] 커뮤니티 리스트 페이지 카테고리 필터링 적용 + post 페이지 기능구현
  src/api/posts.ts
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/(community)/(components)/CommunityMenu.tsx
  src/app/(community)/(components)/PostForm.tsx
  src/app/(community)/community-list/page.tsx
  src/app/(community)/community-post/page.tsx
  src/app/(non-auth)/login/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layout/Header.tsx
  src/hooks/useAuth.ts
  src/types/posts.ts
  src/utils/date.ts
Labels: 개발

#36 [feat] 서브 헤더 공통 컴포넌트화
  src/app/(quiz)/(components)/Header.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/(quiz)/quiz-form/page.tsx
  src/components/common/BlueInput.tsx
  src/components/common/SubHeader.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
Labels: 개발, 수정

#37 [feat] 사용자 정보 패칭, 이용약관 페이지 구현
  src/app/(non-auth)/login/page.tsx
  src/app/(non-auth)/terms/page.tsx
  src/app/page.tsx
Labels: 개발, 수정

#38 [feat] 선택지 체크 시 정답으로 설정, 헤더 로고 클릭 시 홈으로 이동
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
  src/components/layout/Header.tsx
Labels: 개발

#39 [style] Header & Footer 위치 fixed 및 스타일 조정
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/(quiz)/(components)/QuizList.tsx
  src/app/(quiz)/(components)/SelectQuizLevel.tsx
  src/app/(quiz)/quiz-list/page.tsx
  src/components/common/SubHeader.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
Labels: 수정

#40 [feat] 이미지 미리보기, url setState
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
  src/types/quizzes.ts
Labels: 개발

#41 [feat] 메뉴 구현
  src/app/(non-auth)/terms/page.tsx
  src/app/menu/page.tsx
  src/components/layout/Header.tsx
  src/constant/PrivacyPolicy.tsx
  src/constant/Terms.tsx
  src/hooks/useAuth.ts
  src/store/store.ts
Labels: 개발, 수정

#42 [fix] 이미지 첨부 시 마지막 문제로만 업로드되는 오류 해결
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
Labels: 버그

#45 [style] title, options CSS 작업
  src/app/(quiz)/(components)/QuestionForm.tsx
Labels: 개발

#46 [style] quiz-form 페이지 퀴즈 input 스타일 수정
  src/api/quizzes.ts
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/(quiz)/(components)/QuizList.tsx
  src/app/(quiz)/(components)/SelectQuizLevel.tsx
  src/app/(quiz)/mutations.tsx
  src/components/common/BlueInput.tsx
  src/components/common/FormButtons.tsx
  src/components/common/PageUpBtn.tsx
  src/types/quizzes.ts
Labels: 개발, 수정

#47 [fix] 이미지 input DOM id 인식 오류 해결 - DOM 직접 접근 말고 label 로 연결
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
Labels: 수정, 버그

#49 [feat] 메뉴 모달창 페이지 이동시 자동 닫힘 구현
  src/app/menu/page.tsx
  src/components/layout/Header.tsx
Labels: 개발

#50 [style] question CSS, tailwind.config 에 backgroundSize 추가
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
  tailwind.config.ts
Labels: 개발, 세팅

#51 [feat] question 내 중복 태그들 컴포넌트로 분리
  src/app/(quiz)/(components)/InputQuestionImg.tsx
  src/app/(quiz)/(components)/InputQuestionTitle.tsx
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/SelectQuestionType.tsx
  src/app/(quiz)/quiz-try/page.tsx
  src/components/common/SubHeader.tsx
Labels: 수정

#52 [fix] Worning: prop 'id' did not match. useEffect 로 해결
  src/app/(quiz)/(components)/QuestionForm.tsx
Labels: 수정, 버그

#53 [feat] 회원가입 페이지 css 변경 소셜 로그인 정보 추가 구현
  src/app/(non-auth)/login/page.tsx
  src/app/(non-auth)/signup/page.tsx
  src/app/(non-auth)/terms/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/components/layout/Header.tsx
  src/hooks/useAuth.ts
  yarn.lock
Labels: 개발, 수정

#54 [feat] 게시글 좋아요 기능
  src/app/(community)/(components)/CommentForm.tsx
  src/app/(community)/(components)/CommentList.tsx
  src/app/(community)/(components)/Like.tsx
  src/app/(community)/(components)/LikeToggleButton.tsx
  src/app/(community)/community-list/[id]/page.tsx
  src/components/layout/Header.tsx
  src/hooks/useAuth.ts
  src/types/posts.ts
Labels: 개발, 수정

#57 [fix] 댓글 무한 랜더링 버그 수정
  src/app/(community)/(components)/Comment.tsx
  src/app/(community)/(components)/CommentForm.tsx
  src/app/(community)/(components)/CommentList.tsx
  src/app/(community)/community-list/[id]/page.tsx
  yarn.lock
Labels: 버그

#59 [feat/style] quiz-try 레이아웃 구성 중, 메인 레이아웃 height vh 로 변경
  src/app/(community)/community-list/page.tsx
  src/app/(quiz)/quiz-try/page.tsx
  src/components/common/SubHeader.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
Labels: 개발, 수정

#60 [style] 퀴즈 풀기 페이지 큰 레이아웃 마무리, 공통 Header 정렬 수정, Footer 깃허브&인스타 링크 연결
  src/app/(quiz)/quiz-try/page.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
Labels: 수정

#61 [feat] image 파일 supabase 에 업로드 / post option -> radio 변경
  package.json
  src/app/(community)/(components)/CommunityMenu.tsx
  src/app/(community)/(components)/NoticeEditor.tsx
  src/app/(community)/(components)/PostForm.tsx
  yarn.lock
Labels: 개발

#62 [feat] 타자 연습 게임 초기 구현
  src/app/(non-auth)/login/page.tsx
  src/app/(non-auth)/signup/page.tsx
  src/app/menu/page.tsx
  src/app/page.tsx
  src/app/typing-game/page.tsx
  src/components/layout/Header.tsx
  src/types/word.ts
  src/utils/wordList.ts
Labels: 개발, 수정

#63 [feat] quizzes 테이블에서 불러와서 출력
  next.config.mjs
  src/api/quizzes.ts
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/(quiz)/(components)/QuizList.tsx
  src/app/(quiz)/(components)/SelectQuizLevel.tsx
  src/app/(quiz)/quiz-list/page.tsx
Labels: 개발, 수정

#64 [fix] question 문제, 선택지, 주관식 정답 input 최대 글자수 제한 및 입력한 글자수 표시
  src/app/(quiz)/(components)/InputQuestionTitle.tsx
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/utils/handleMaxLength.ts
Labels: 개발, 수정, 버그

#65 [style] 타자연습 페이지 레이아웃 CSS
  src/app/typing-game/page.tsx
Labels: 수정

#67 [feat] 현재 로그인한 유저의 이메일로 퀴즈만들기
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/(quiz)/(components)/QuizList.tsx
  src/components/common/BlueInput.tsx
  src/components/layout/Footer.tsx
  src/utils/wordList.ts
Labels: 개발, 수정

#68 [feat] quiz/[id]로 폴더 구조 변경, params 받아 퀴즈 데이터 불러옴
  src/api/questions.ts
  src/api/quizzes.ts
  src/app/(quiz)/(components)/QuizList.tsx
  src/app/(quiz)/quiz-try/page.tsx
  src/app/(quiz)/quiz/[id]/page.tsx
  src/types/quizzes.ts
Labels: 개발, 수정

#70 [feat] quiz-list 페이지 스타일 조정
  src/app/(quiz)/(components)/QuizList.tsx
  src/app/(quiz)/(components)/SelectQuizLevel.tsx
  src/app/(quiz)/quiz-list/page.tsx
  src/assets/level1.png
  src/assets/level2.png
  src/assets/level3.png
  src/components/common/test.tsx
Labels: 수정

#71 [feat] 레벨 선택 시 레벨 카드 위치 고정
  src/app/(auth)/mypage/page.tsx
  src/app/(quiz)/(components)/SelectQuizLevel.tsx
  src/app/admin/page.tsx
  src/app/page.tsx
  src/components/common/FormButtons.tsx
Labels: 개발, 수정

#72 [feat] 페이지네이션 기능 구현
  src/api/posts.ts
  src/app/(community)/(components)/CategorySelector.tsx
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/(community)/(components)/NoticeEditor.tsx
  src/app/(community)/(components)/PostForm.tsx
  src/app/(community)/community-list/page.tsx
  src/app/(community)/community-post/page.tsx
  src/types/posts.ts
Labels: 개발

#74 Feat/quiz try
  src/api/posts.ts
  src/api/question_options.ts
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizList.tsx
  src/app/(quiz)/quiz/[id]/Options.tsx
  src/app/(quiz)/quiz/[id]/page.tsx
  src/app/menu/page.tsx
  src/components/layout/Header.tsx
Labels: 개발

#75 [chore] supabase storage 주소 변수화
  src/app/(quiz)/(components)/QuizForm.tsx
  src/components/common/BlueInput.tsx
  src/constant/test.tsx
  src/hooks/useConfirmPageLeave.tsx
  src/utils/supabase/storage.ts
Labels: 수정

#76 [fix] 메인 헤더에 메뉴 표시 및 링크 연결
  src/components/layout/Header.tsx
Labels: 수정

#78 [feat] quiz-form 새로고침/브라우저 닫을 때 경고
  src/app/(quiz)/(components)/QuizForm.tsx
  src/hooks/useConfirmPageLeave.tsx
Labels: 개발

#79 [fix] 문제마다 같은 옵션 불러와지는 에러
  src/app/(quiz)/quiz/[id]/Options.tsx
  src/app/(quiz)/quiz/[id]/page.tsx
Labels: 수정, 버그

#80 [fix] 퀘스천 제목, 정답들이 비어있거나 선택형에서 정답 체크가 안되있을 시 워닝 toast
  src/app/(quiz)/(components)/QuizForm.tsx
Labels: 개발, 수정

#81 [feat] 난이도 추가 및 난이도 조절
  src/app/page.tsx
  src/app/typing-game/page.tsx
  src/components/layout/Header.tsx
  src/types/word.ts
  src/utils/wordList.ts
Labels: 개발, 수정

#82 [fix] 헤더 메뉴 다시 추가
  src/components/layout/Header.tsx
Labels: 수정

#83 [fix] 커뮤니티 카테고리 메뉴 수정
  src/api/posts.ts
  src/app/(community)/(components)/CategorySelector.tsx
  src/app/(community)/(components)/Comment.tsx
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/(community)/(components)/CommunityMenu.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(community)/community-list/[category]/[id]/page.tsx
  src/app/(community)/community-list/page.tsx
  src/app/menu/page.tsx
  src/app/page.tsx
  src/components/layout/Header.tsx
  src/types/posts.ts
Labels: 개발, 수정

#84 [feat] quiz&question form 첨부 이미지 삭제하기 기능 구현
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/(quiz)/(components)/UnloadImg.tsx
  src/components/common/BlueInput.tsx
  src/hooks/useConfirmPageLeave.tsx
Labels: 개발

#86 [style] profile 페이지 UI 완성
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/profile/MyLevelAndScore.tsx
  src/app/profile/MyProfile.tsx
  src/app/profile/VerticalBlueLine.tsx
  src/app/profile/page.tsx
Labels: 개발

#88 [feat] 메인 페이지 구현
  src/api/posts.ts
  src/api/quizzes.ts
  src/app/(main)/(components)/CommunitySection.tsx
  src/app/(main)/(components)/MainLogo.tsx
  src/app/(main)/(components)/QuizSection.tsx
  src/app/(main)/(components)/RankingSection.tsx
  src/app/page.tsx
  src/assets/mainimage.jpeg
  src/components/layout/Header.tsx
Labels: 개발

#89 [fix] is_correct 추가 말고, 사용자가 답을 입력하면 userAnswer 상태에 저장하는 방식으로 변경
  src/app/(main)/(components)/CommunitySection.tsx
  src/app/(quiz)/quiz/[id]/Options.tsx
  src/app/(quiz)/quiz/[id]/page.tsx
Labels: 개발, 수정

#90 [feat] 결과 페이지에서 주관형 정답/오답 조건부 렌더링
  src/app/(quiz)/quiz/[id]/page.tsx
Labels: 개발

#91 [feat] 메인 페이지 퀴즈 수정, 타자 연습 랭킹 구현
  src/api/game_scrore.ts
  src/api/questions.ts
  src/app/(main)/(components)/CommunitySection.tsx
  src/app/(main)/(components)/QuestionEx.tsx
  src/app/(main)/(components)/QuizSection.tsx
  src/app/(main)/(components)/RankingSection.tsx
  src/app/typing-game/page.tsx
  src/components/layout/Header.tsx
Labels: 개발, 수정

#93 [fix] 메인페이지 css수정
  src/app/(main)/(components)/CommunitySection.tsx
Labels: 수정

#94 [feat] 결과 페이지에서 선택형 정답/오답 조건부 렌더링 및 좌측 퀴즈 정보 비율 16%로 수정
  src/app/(quiz)/quiz/[id]/Header.tsx
  src/app/(quiz)/quiz/[id]/Options.tsx
  src/app/(quiz)/quiz/[id]/page.tsx
  src/components/layout/Header.tsx
  src/types/quizzes.ts
  tailwind.config.ts
Labels: 개발, 수정

#95 [feat] 메인 페이지 Footer
  src/app/(main)/(components)/Footer.tsx
  src/app/(quiz)/(components)/QuizList.tsx
  src/app/page.tsx
Labels: 개발

#96 [feat] 커뮤니티 css 수정 / 이미지 사이즈 조절 / 수정페이지 접근
  package.json
  src/api/posts.ts
  src/app/(community)/(components)/CategorySelector.tsx
  src/app/(community)/(components)/Comment.tsx
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(community)/(components)/EditForm.tsx
  src/app/(community)/(components)/Like.tsx
  src/app/(community)/(components)/NoticeEditor.tsx
  src/app/(community)/(components)/PostForm.tsx
  src/app/(community)/community-list/[category]/[id]/edit/page.tsx
  src/app/(community)/community-list/page.tsx
  src/app/(community)/community-post/page.tsx
  src/components/common/FormButtons.tsx
  src/components/common/PostDeleteButton.tsx
  src/components/common/PostEditButton.tsx
  src/types/posts.ts
  tailwind.config.ts
  yarn.lock
Labels: 개발, 수정, 세팅

#97 [feat] 퀴즈 만든 수 랭킹 구현 , 버그수정
  src/api/quizzes.ts
  src/app/(main)/(components)/CommunitySection.tsx
  src/app/(main)/(components)/RankingSection.tsx
  src/app/typing-game/page.tsx
  src/types/quizzes.ts
Labels: 개발, 버그

#98 [feat] supabase SSR 방식으로 변경... 그리고 헤더 수정
  middleware.ts
  src/app/(community)/community-list/page.tsx
  src/app/(main)/(components)/CommunitySection.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/components/layout/Header.tsx
  src/hooks/useAuth.ts
  src/types/users.ts
  src/utils/supabase/client.ts
  src/utils/supabase/create-client.ts
  src/utils/supabase/supabase.ts
Labels: 개발, 수정

#99 [fix/style] quiz-form 페이지 input 텍스트 컬러 변경 & 선택형 문제일 때만 options 업로드 & 페이지업 버튼 수정
  next.config.mjs
  package.json
  src/app/(community)/community-list/page.tsx
  src/app/(quiz)/(components)/InputQuestionTitle.tsx
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
  src/assets/arrow_circle_right_FILL1_wght400_GRAD0_opsz24.svg
  src/components/common/BlueInput.tsx
  src/components/common/PageUpBtn.tsx
  yarn.lock
Labels: 수정, 세팅, 버그

#100 [style] 헤더 로그인 로그아웃 디자인 변경
  package.json
  src/app/layout.tsx
  src/app/provider.tsx
  src/app/typing-game/page.tsx
  src/components/layout/Header.tsx
  tailwind.config.ts
  yarn.lock
Labels: 개발

#101 [refactor] 세션에서 사용자 확인하여 creator_id 설정
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/profile/page.tsx
  yarn.lock
Labels: 수정

#102 [feat] 커뮤니티 메인페이지 403 에러 처리
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(community)/(components)/EditForm.tsx
  src/app/(community)/(components)/NoticeEditor.tsx
  src/app/(community)/community-list/page.tsx
Labels: 버그

#103 [fix] 소셜 로그인 회원가입 로직 수정
  src/app/page.tsx
  src/components/layout/Header.tsx
Labels: 개발, 수정, 버그

#104 [feat] profile 페이지에서 로그인 유저의 정보 불러오기
  src/app/profile/MyProfile.tsx
  src/app/profile/page.tsx
Labels: 개발

#107 [feat] 카테고리별 게시글 총 개수 표시 및 상세 403 에러 처리
  package.json
  src/app/(community)/(components)/CategorySelector.tsx
  src/app/(community)/(components)/Comment.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(community)/(components)/Like.tsx
  src/app/(community)/(components)/LikeToggleButton.tsx
  src/app/(main)/(components)/RankingSection.tsx
  src/app/menu/page.tsx
  src/types/posts.ts
  yarn.lock
Labels: 개발, 수정, 버그

#110 [feat] 타자연습 로그인 확인 모달
  src/app/typing-game/page.tsx
Labels: 개발

#111 [fix] footer 깃허브, 인스타 문구 아이콘으로 변경
  src/app/(main)/(components)/Footer.tsx
  src/app/(main)/(components)/MainLogo.tsx
  src/app/(main)/(components)/QuizSection.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/provider.tsx
  src/app/typing-game/page.tsx
  src/assets/github_icon.png
  src/assets/instagram_icon.png
  src/components/layout/Footer.tsx
  yarn.lock
Labels: 수정

#112 [feat] 퀴즈 리스트에서 로그인 여부 확인 & 만들기 클릭 시 로그인 필요 알림 toast & 퀴즈 풀기 Link =>
  src/app/(quiz)/(components)/QuizList.tsx
  src/app/(quiz)/(components)/SelectQuizLevel.tsx
  src/components/common/RecommendLoginModal.tsx
  src/store/store.ts
Labels: 개발

#113 [feat] 풀기 페이지에 퀴즈 작성자 정보 email => nickname 으로 변경
  src/api/profiles.ts
  src/app/(quiz)/quiz/[id]/Creator.tsx
  src/app/(quiz)/quiz/[id]/page.tsx
Labels: 개발, 수정

#114 [feat] 프로필 페이지 수정 중
  src/api/game_scrore.ts
  src/api/quizzes.ts
  src/api/users.ts
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/profile/MyLevelAndScore.tsx
  src/app/profile/MyProfile.tsx
  src/app/profile/page.tsx
  src/hooks/useAuth.ts
  src/types/users.ts
  src/utils/supabase/storage.ts
Labels: 개발

#116 [feat] 프로필 수정하기 구현 완료
  src/api/users.ts
  src/app/profile/MyLevelAndScore.tsx
  src/app/profile/MyProfile.tsx
  src/app/profile/mutations.tsx
  src/app/profile/page.tsx
  src/types/users.ts
Labels: 개발, 수정

#117 [feat] 중복 이메일 가입 방지 , 타자 연습 모달 버튼 위치 수정
  src/app/(non-auth)/signup/page.tsx
  src/app/admin/page.tsx
  src/app/typing-game/page.tsx
  src/hooks/useAuth.ts
Labels: 개발, 수정

#118 [fix] 로그인시 사용자 정보 없을때만 정보 저장 로직 실행
  src/app/page.tsx
  src/components/layout/Header.tsx
Labels: 개발, 수정

#119 [feat] 퀴즈 점수 DB 에 insert, 풀었던 문제라면 update
  src/api/tries.ts
  src/app/(quiz)/quiz/[id]/Creator.tsx
  src/app/(quiz)/quiz/[id]/mutation.ts
  src/app/(quiz)/quiz/[id]/page.tsx
  src/types/quizzes.ts
Labels: 개발

#120 [fix] 퀴즈 풀기 페이지 로그인 확인 & 프로필 요청 useEffect 분리, 의존성 배열 수정
  src/api/tries.ts
  src/app/(quiz)/quiz/[id]/Creator.tsx
  src/app/(quiz)/quiz/[id]/page.tsx
  src/types/quizzes.ts
Labels: 수정, 버그

#121 [fix] 사용자가 이미지를 등록하지 않은 question 은 기본 이미지도 표시 X
  src/app/(quiz)/quiz/[id]/Creator.tsx
  src/app/(quiz)/quiz/[id]/page.tsx
Labels: 개발, 수정

#122 [style] quiz-list 페이지 레벨 카드 스타일 조정
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/(quiz)/(components)/SelectQuizLevel.tsx
  src/app/profile/MyProfile.tsx
  src/assets/level1.png
  src/assets/level2.png
  src/assets/level3.png
Labels: 수정

#124 [feat] my-activity 페이지 quiz, post 데이터 불러오기
  src/api/posts.ts
  src/api/quizzes.ts
  src/app/(community)/community-list/page.tsx
  src/app/my-activity/MyActivity.tsx
  src/app/my-activity/page.tsx
  src/types/quizzes.ts
  yarn.lock
Labels: 개발

#123 [style] 로그인/회원가입 페이지 메인 영역 높 84vh 조정
  src/app/(main)/(components)/RankingSection.tsx
  src/app/(non-auth)/login/page.tsx
  src/app/(non-auth)/signup/page.tsx
  src/app/(non-auth)/terms/page.tsx
Labels: 수정

#127 [feat] 랭킹 로직 수정
  src/api/game_scrore.ts
  src/api/tries.ts
  src/app/(main)/(components)/RankingSection.tsx
  src/types/quizzes.ts
Labels: 개발, 수정, 버그

#128 [feat] 랭킹 로직 수정 진짜 최종
  src/api/game_scrore.ts
  src/api/tries.ts
  src/app/(main)/(components)/RankingSection.tsx
  src/app/typing-game/page.tsx
  src/types/game.ts
Labels: 개발, 버그

#129 [feat] 소개페이지 및 query 수정
  src/api/comment.ts
  src/api/likes.ts
  src/api/posts.ts
  src/api/users.ts
  src/app/(community)/(components)/CategorySelector.tsx
  src/app/(community)/(components)/Comment.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(community)/(components)/Like.tsx
  src/app/(community)/(components)/mutations.tsx
  src/app/(community)/community-list/page.tsx
  src/app/about/page.tsx
  src/types/posts.ts
Labels: 개발, 수정, 버그

#130 [feat] my-activity 페이지 카테고리별 해당된 버튼 기능 추가
  src/api/comments.ts
  src/api/posts.ts
  src/app/(community)/(components)/Comment.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/my-activity/MyActivity.tsx
  src/components/common/DeleteButton.tsx
  src/components/common/EditButton.tsx
  src/components/common/PostDeleteButton.tsx
  src/types/posts.ts
Labels: 개발, 문서

#131 [fix/feat] 퀴즈 풀기 들어가면 다른 퀴즈 정보가 잠깐 뜨는 오류 & 주관형 답안 입력 글자수 표시
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/quiz/[id]/page.tsx
Labels: 개발, 수정, 버그

#132 [fix]커뮤니티 useEffect -> query 수정
  src/api/likes.ts
  src/app/(community)/(components)/CategorySelector.tsx
  src/app/(community)/(components)/Like.tsx
  src/app/(community)/(components)/mutations.tsx
Labels: 수정, 버그

#133 [feat] my-activity CSS
  src/app/my-activity/MyActivity.tsx
  src/components/common/DeleteButton.tsx
Labels: 수정

#134 [style] 프로필 이미지 동그라미로 수정
  src/app/(community)/(components)/Comment.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(main)/(components)/RankingSection.tsx
  src/components/layout/Header.tsx
Labels: 수정

#135 [style] 폰트 Gothic A1 으로 변경
  src/api/quizzes.ts
  src/app/(main)/(components)/Footer.tsx
  src/app/layout.tsx
  src/app/styles/font.ts
  src/app/typing-game/page.tsx
  tailwind.config.ts
Labels: 개발, 수정

#136 [style] 메인페이지 스타일 조정
  src/app/(main)/(components)/CommunitySection.tsx
  src/app/(main)/(components)/Footer.tsx
  src/app/(main)/(components)/MainLogo.tsx
  src/app/(main)/(components)/QuizSection.tsx
  src/app/(main)/(components)/RankingSection.tsx
  src/app/(quiz)/(components)/QuizList.tsx
  src/app/(quiz)/(components)/SelectQuizLevel.tsx
  src/app/page.tsx
  src/assets/logo_horizontal_1.png
  src/assets/logo_vertical_3.png
  src/components/layout/Header.tsx
Labels: 수정

#137 [style] quiz-list 페이지 레벨 카드 삽입
  src/app/(main)/(components)/Footer.tsx
  src/app/(quiz)/(components)/SelectQuizLevel.tsx
  src/assets/level1.png
  src/assets/level2.png
  src/assets/level3.png
Labels: 수정

#138 [style] 프로필 페이지 CSS 수정, 페이지업 버튼 스타일 변경
  src/api/tries.ts
  src/app/profile/MyLevelAndScore.tsx
  src/app/profile/MyProfile.tsx
  src/components/common/PageUpBtn.tsx
Labels: 수정

#139 [style] 퀴즈 레벨 이미지 기울임, 겹치기, 보더 스타일 조정
  src/app/(quiz)/(components)/SelectQuizLevel.tsx
Labels: 수정

#140 [feat] about 페이지 css 적용
  src/api/quizzes.ts
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(community)/(components)/Like.tsx
  src/app/(community)/(components)/mutations.tsx
  src/app/about/page.tsx
  src/app/my-activity/MyActivity.tsx
Labels: 개발, 수정

#141 [feat] 회원가입 기본 이미지 변경, 나의 활동 메뉴 추가 , 회원가입 및 헤더 에러 수정
  src/app/(main)/(components)/QuizSection.tsx
  src/app/(non-auth)/login/page.tsx
  src/app/(non-auth)/signup/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/components/layout/Header.tsx
  src/hooks/useAuth.ts
  src/utils/supabase/storage.ts
Labels: 개발, 수정, 버그

#142 [feat] 프로필 퀴즈점수 불러오기, 합한 점수 표시
  src/api/reports.ts
  src/api/tries.ts
  src/app/profile/MyLevelAndScore.tsx
  src/components/layout/Header.tsx
Labels: 개발

#143 [fix] 타자연습 점수 누적 삭제
  src/app/(non-auth)/signup/page.tsx
  src/app/admin/page.tsx
  src/app/typing-game/page.tsx
Labels: 개발, 수정

#144 [style] 로그인,회원가입 이미지 수정, 타자연습 점수저장 로직 수정
  src/app/(non-auth)/login/page.tsx
  src/app/(non-auth)/signup/page.tsx
  src/app/typing-game/page.tsx
Labels: 개발, 수정

#145 [feat] 커뮤니티 게시글 조회수 기능 구현
  src/api/posts.ts
  src/app/(community)/(components)/Comment.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(community)/(components)/Like.tsx
  src/app/(community)/(components)/mutations.tsx
  src/app/about/page.tsx
  src/hooks/useAuth.ts
  src/types/posts.ts
Labels: 개발

#146 [feat] my-activtiy 내가 푼 퀴즈 불러오기
  src/api/quizzes.ts
  src/app/my-activity/MyActivity.tsx
Labels: 개발, 수정

#147 [refactor] 프로필 페이지 데이터 가져오기 전체적으로 수정
  src/api/tries.ts
  src/app/(quiz)/(components)/SelectQuizLevel.tsx
  src/app/profile/MyLevelAndScore.tsx
  src/app/profile/MyProfile.tsx
  src/app/profile/page.tsx
  src/assets/face_2.png
  src/assets/level1.png
  src/assets/level2.png
  src/assets/level3.png
  src/components/common/SubHeader.tsx
  src/components/layout/Header.tsx
  src/components/layout/ProfileDropdown.tsx
Labels: 수정

#148 [style] quiz-form 페이지 파일첨부 이전 기본이미지 적용
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
  src/components/common/BlueInput.tsx
  src/components/common/SubHeader.tsx
Labels: 수정

#149 [feat] 소개페이지 이미지추가 및 css
  src/app/(non-auth)/login/page.tsx
  src/app/about/page.tsx
  src/assets/info_icon_1.png
  src/assets/info_icon_2.png
  src/assets/info_icon_3.png
  src/assets/team/info_HM.png
  src/assets/team/info_JM.png
  src/assets/team/info_JY.png
  src/assets/team/info_SH.png
  src/assets/team/info_YJ.png
  src/assets/team/info_YS.png
  src/assets/team/info_people.png
Labels: 수정

#150 [style] quiz-form 랜덤 기본 썸네일 지정, quiz-list 퀴즈 배열 수정
  src/api/quizzes.ts
  src/app/(main)/(components)/QuestionEx.tsx
  src/app/(main)/(components)/QuizSection.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
  src/app/(quiz)/(components)/QuizList.tsx
  src/app/(quiz)/quiz/[id]/page.tsx
  src/utils/getRandomThumbnail.ts
Labels: 수정

#151 [style] about페이지, profile페이지 정말 소소한 스타일 수정
  src/app/(main)/(components)/CommunitySection.tsx
  src/app/about/page.tsx
  src/app/profile/MyProfile.tsx
  src/app/typing-game/page.tsx
  src/assets/logo_horizontal_3.png
  src/components/common/RecommendLoginModal.tsx
Labels: 수정

#152 [feat] my-activity 조회수추가, 페이지네이션 / 커뮤니티 페이지 조회수 추가
  src/app/(community)/(components)/CategorySelector.tsx
  src/app/(community)/(components)/Comment.tsx
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(community)/(components)/EditForm.tsx
  src/app/(community)/(components)/NoticeEditor.tsx
  src/app/(community)/(components)/PostForm.tsx
  src/app/(community)/community-list/page.tsx
  src/app/about/page.tsx
  src/app/globals.css
  src/app/my-activity/MyActivity.tsx
  src/app/my-activity/Pagination.tsx
  src/components/layout/Footer.tsx
  src/types/pagination.ts
  src/types/posts.ts
Labels: 개발, 수정

#154 Feat/quiz reports
  src/api/admin.ts
  src/api/reports.ts
  src/api/tries.ts
  src/app/(quiz)/quiz/[id]/mutations.ts
  src/app/(quiz)/quiz/[id]/page.tsx
  src/types/admin.ts
Labels: 개발, 수정

#155 [feat] 로그인 여부, 신고 등록 이력(admin) 여부, 현재 사용자의 신고(reports) 여부에 따른 신고 처리
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(quiz)/quiz/[id]/page.tsx
  src/components/common/ReportButton.tsx
Labels: 개발

#156 [feat] 커뮤니티 신고 기능 추가
  src/api/posts.ts
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(community)/community-list/page.tsx
  src/app/profile/MyLevelAndScore.tsx
  src/components/common/ReportButton.tsx
  src/types/posts.ts
Labels: 개발

#157 [feat] 어드민 페이지 신고글 불러오기 및 제목 클릭시 이동 구현
  src/api/admin.ts
  src/app/admin/page.tsx
  src/types/admin.ts
Labels: 개발

#158 [feat] 어드민 조건부로 헤더에 표시
  src/app/admin/page.tsx
  src/components/layout/Header.tsx
  src/types/users.ts
Labels: 개발

#159 [test] 배포테스트 yarn build
  src/app/(community)/(components)/CommunityMain.tsx
  src/app/(community)/community-list/page.tsx
  src/app/about/page.tsx
  src/app/menu/page.tsx
  src/constant/Terms.tsx
Labels: 수정, 버그

#160 [feat] 신고 삭제 복구 구현
  src/app/admin/page.tsx
Labels: 개발

#163 [style] 소개페이지 유저후기 말풍선 css
  src/app/about/page.tsx
  src/app/globals.css
Labels: 수정

#164 [style] 배너 랜덤 설정 및 커뮤니티 좋아요/신고 CSS 수정
  src/app/(community)/(components)/CommunityMain.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(community)/(components)/Like.tsx
  src/app/(main)/(components)/Banner.tsx
  src/app/(main)/(components)/MainLogo.tsx
  src/app/(main)/(components)/QuizSection.tsx
  src/app/(quiz)/(components)/InputQuestionImg.tsx
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/page.tsx
  src/components/common/ReportButton.tsx
  tailwind.config.ts
Labels: 개발, 수정

#165 [feat] 커뮤니티 공지 구현
  src/app/(community)/(components)/CategorySelector.tsx
  src/app/(community)/(components)/PostForm.tsx
  src/assets/mainimage.jpeg
Labels: 개발

#166 [style] 커뮤니티 페이지 css
  src/app/(community)/(components)/CategorySelector.tsx
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/(community)/(components)/CommunityMain.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
Labels: 수정

#167 [style] 커뮤니티 css 수정
  src/app/(community)/(components)/CategorySelector.tsx
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/(community)/(components)/CommunityMain.tsx
Labels: 수정

#168 [feat] 메인페이지 공지 표시
  src/api/posts.ts
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/(main)/(components)/CommunitySection.tsx
Labels: 개발

#169 [feat] 파비콘 추가
  public/favicon.png
  src/app/(non-auth)/terms/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
Labels: 수정

#170 [style] 사이트소개 페이지 css 수정
  src/app/(community)/(components)/CategorySelector.tsx
  src/app/about/page.tsx
  src/app/admin/page.tsx
Labels: 수정

#171 [style] 모달 css 수정
  src/app/typing-game/page.tsx
  src/components/common/RecommendLoginModal.tsx
Labels: 수정

#172 [feat] 타자 연습 헤더 조건부 렌더링
  src/app/typing-game/page.tsx
  src/components/layout/Header.tsx
Labels: 수정

#173 [feat] 랭킹 일주일 단위로 수정
  src/api/game_scrore.ts
  src/api/quizzes.ts
  src/api/tries.ts
  src/app/typing-game/page.tsx
  src/utils/date.ts
Labels: 개발

#174 [feat] 퀴즈 풀기 페이지에서 내가만든 퀴즈인경우 삭제 구현
  src/api/quizzes.ts
  src/app/(quiz)/quiz/[id]/mutations.ts
  src/app/(quiz)/quiz/[id]/page.tsx
Labels: 개발

#175 [fix] 나의 프로필 페이지 퀴즈 점수 불러오기 에러 해결
  src/api/tries.ts
  src/app/profile/MyLevelAndScore.tsx
  src/types/quizzes.ts
Labels: 수정, 버그

#176 [feat] 관리자 페이지 조건부 랜더링 및 나의 활동 오류수정
  src/api/quizzes.ts
  src/app/admin/page.tsx
  src/app/my-activity/MyActivity.tsx
  src/hooks/useAuth.ts
Labels: 개발, 버그

#177 [fix] 로딩 메세지 수정
  src/app/profile/MyLevelAndScore.tsx
Labels: 수정

#178 [style] 퀴즈리스트 보더 색상
  src/app/(quiz)/(components)/QuizList.tsx
Labels: 수정

#179 [feat] 타자연습 난이도 명 변경, 커뮤니티 공지 상단 고정
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/typing-game/page.tsx
  src/types/difficultySetting.ts
Labels: 개발, 수정

#180 [style] 소개페이지 css 변경사항 수정
  src/app/about/page.tsx
  src/app/globals.css
Labels: 수정

#181 [feat] 신고버튼 위치 조정 / 공지글 색 변경
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/(community)/(components)/CommunityMain.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(community)/(components)/PostForm.tsx
  src/app/(quiz)/quiz/[id]/mutations.ts
  src/app/my-activity/MyActivity.tsx
  src/components/common/ReportButton.tsx
Labels: 수정

#182 [feat] 나의 프로필에 총 점수에 따라 level 표시
  src/app/profile/MyLevelAndScore.tsx
Labels: 개발

#183 [fix]소개페이지 팀 정보 버튼 수정
  src/app/about/page.tsx
Labels: 수정

#184 [feat] 메인페이지 퀴즈 최신순 수정, 커뮤니티 관리자 삭제버튼 추가
  src/api/posts.ts
  src/api/quizzes.ts
  src/app/(community)/(components)/CommunityForm.tsx
  src/app/(community)/(components)/DetailPost.tsx
  src/app/typing-game/page.tsx
Labels: 개발

#185 [fix] 문제, 옵션 현재 최대 갯수라면 추가 버튼 회색으로 표시 & footer CSS
  src/app/(main)/(components)/Footer.tsx
  src/app/(quiz)/(components)/PlusQuestionBtn.tsx
  src/app/(quiz)/(components)/QuestionForm.tsx
  src/app/(quiz)/(components)/QuizForm.tsx
  src/assets/logo_vertical_4.png
  src/components/layout/Footer.tsx
  tailwind.config.ts
Labels: 개발, 수정

#186 [style] game 배경이미지 추가
  src/app/typing-game/page.tsx
  src/utils/supabase/storage.ts
  tailwind.config.ts
Labels: 수정

#187 [style] 메뉴 호버,선택시 밑줄 생성
  src/app/typing-game/page.tsx
  src/components/layout/Header.tsx
  tailwind.config.ts
Labels: 수정

#188 [feat] 문제 페이지네이션 기능 구현 및 버튼 구성 & 결과 페이지에선 모든 문제 표시
  src/app/(quiz)/quiz/[id]/Options.tsx
  src/app/(quiz)/quiz/[id]/page.tsx
Labels: 개발, 수정

#189 [feat] quiz 기능 전체적으로 페이지 라우팅 구조 변경
  src/api/quizzes.ts
  src/app/(main)/(components)/QuizSection.tsx
  src/app/quiz/[id]/Creator.tsx
  src/app/quiz/[id]/Header.tsx
  src/app/quiz/[id]/Options.tsx
  src/app/quiz/[id]/mutations.ts
  src/app/quiz/[id]/page.tsx
  src/app/quiz/form/InputQuestionImg.tsx
  src/app/quiz/form/InputQuestionTitle.tsx
  src/app/quiz/form/PlusQuestionBtn.tsx
  src/app/quiz/form/QuestionForm.tsx
  src/app/quiz/form/QuizForm.tsx
  src/app/quiz/form/SelectQuestionType.tsx
  src/app/quiz/form/UnloadImg.tsx
  src/app/quiz/form/page.tsx
  src/app/quiz/list/QuizList.tsx
  src/app/quiz/list/SelectQuizLevel.tsx
  src/app/quiz/list/page.tsx
  src/app/quiz/mutations.tsx
  src/components/common/ReportButton.tsx
Labels: 문서

#190 [fix] 헤더 퀴즈 페이지 링크 수정
  src/app/quiz/list/SelectQuizLevel.tsx
  src/components/layout/Header.tsx
Labels: 문서

#191 [feat] 커뮤니티 전체 코드 리팩토링 / 폴더 구조 변경
  src/app/(community)/(components)/DetailPost.tsx
  src/app/(community)/(components)/EditForm.tsx
  src/app/(community)/(components)/PostForm.tsx
  src/app/(community)/community-list/[category]/[id]/edit/page.tsx
  src/app/(community)/community-list/page.tsx
  src/app/(community)/community-post/page.tsx
  src/app/(main)/(components)/CommunitySection.tsx
  src/app/admin/page.tsx
  src/app/community/list/[category]/CategorySelector.tsx
  src/app/community/list/[category]/CommunityForm.tsx
  src/app/community/list/[category]/CommunityMain.tsx
  src/app/community/list/[category]/[id]/Comment.tsx
  src/app/community/list/[category]/[id]/DetailPost.tsx
  src/app/community/list/[category]/[id]/Like.tsx
  src/app/community/list/[category]/[id]/LikeToggleButton.tsx
  src/app/community/list/[category]/[id]/edit/page.tsx
  src/app/community/list/[category]/[id]/page.tsx
  src/app/community/list/[category]/layout.tsx
  src/app/community/list/[category]/page.tsx
  src/app/community/mutations.tsx
  src/app/community/page.tsx
  src/app/community/write/NoticeEditor.tsx
  src/app/community/write/PostEditor.tsx
  src/app/community/write/layout.tsx
  src/app/community/write/page.tsx
  src/app/my-activity/MyActivity.tsx
  src/components/layout/Header.tsx
Labels: 수정, 문서

#192 [feat] 퀴즈 풀기 나가기 버튼 추가 & 주관식 답 입력했다 지워도 제출되는 에러 & 문제 갯수 하나라면 이전/다음 버튼 숨김
  src/app/quiz/[id]/Header.tsx
  src/app/quiz/[id]/page.tsx
Labels: 개발, 수정, 버그

#193 [feat] Header border 유지
  src/app/community/list/[category]/CategorySelector.tsx
  src/app/community/list/[category]/[id]/DetailPost.tsx
  src/components/layout/Header.tsx
Labels: 개발, 버그

#194 [style] tailwind screens lg(min: 1441px), md(min:861px) 설정 & 메인페이지 lg 레이아웃 수정
  src/app/(main)/(components)/CommunitySection.tsx
  src/app/(main)/(components)/QuizSection.tsx
  src/app/(main)/(components)/RankingSection.tsx
  src/app/community/list/[category]/CommunityForm.tsx
  src/app/community/list/[category]/[id]/Comment.tsx
  src/app/layout.tsx
  src/app/my-activity/MyActivity.tsx
  src/app/page.tsx
  src/app/quiz/[id]/page.tsx
  src/app/quiz/form/PlusQuestionBtn.tsx
  src/app/quiz/form/QuestionForm.tsx
  src/app/quiz/form/QuizForm.tsx
  src/app/quiz/list/QuizList.tsx
  src/app/typing-game/page.tsx
  src/components/common/PageUpBtn.tsx
  tailwind.config.ts
Labels: 개발, 수정, 세팅

#195 [feat] 랭킹 날짜 수정
  src/api/game_scrore.ts
  src/api/quizzes.ts
  src/api/tries.ts
  src/types/game.ts
Labels: 수정

#196 [feat] 커뮤니티 css 수정
  src/app/community/list/[category]/[id]/DetailPost.tsx
  src/app/community/list/[category]/[id]/edit/page.tsx
  src/app/community/list/[category]/[id]/page.tsx
  src/app/community/list/[category]/layout.tsx
  src/app/community/list/[category]/page.tsx
  src/app/community/write/PostEditor.tsx
  src/app/community/write/TextEditor.tsx
  src/app/community/write/layout.tsx
  src/app/community/write/page.tsx
Labels: 수정
